language: python
python:
    - "2.7"
install:
    - pip install nose
    - pip install sqlalchemy==1.1
    - pip install psycopg2==2.4.5
    - python setup.py develop
    - sudo -u postgres psql -c "CREATE USER ckan_default WITH PASSWORD 'pass';"
    - sudo -u postgres psql -c 'CREATE DATABASE vdmtest WITH OWNER ckan_default;'	
script: nosetests vdm/sqlalchemy
