language: python
python:
    - "2.7"
install:
    - pip install nose
    - python setup.py develop
    - sudo -u postgres psql -c "CREATE USER ckan_default WITH PASSWORD 'pass';"
    - sudo -u postgres psql -c 'CREATE DATABASE vdmtest WITH OWNER ckan_default;'	
script: nosetests vdm/sqlalchemy
